version: '2'

services:
    nginx:
        image: nginx:1.13.5
        ports:
            - 8011:80
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php

    php:
        build: ./docker/php/
        expose:
            - 9000
        volumes:
            - .:/var/www/html
        links:
            - redis
            - mysql

    mysql:
        image: mysql:latest
        ports:
            - 3306:3306
        volumes:
            - ~/.backup/mysql/laravel-restful-api:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: laravel-restful-api

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - 8012:80
        links:
            - mysql
        environment:
            PMA_HOST: mysql

    redis:
        image: redis:3.2.10
        volumes:
          - ~/.backup/redis/laravel-restful-api:/data



